services:

  postgres:
    image: postgres:16-alpine
    container_name: korp_postgres_dev
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: postgres -c log_min_messages=error
    networks:
      - korp_net

  estoque:
    image: golang:1.25-alpine
    container_name: korp_estoque_dev
    working_dir: /app
    volumes:
      - ./estoque:/app
    command: sh -c "go install github.com/air-verse/air@latest && air"
    ports:
      - "${ESTOQUE_PORT:-5002}:${ESTOQUE_PORT:-5002}"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - korp_net

  faturamento:
    image: golang:1.25-alpine
    container_name: korp_faturamento_dev
    working_dir: /app
    volumes:
      - ./faturamento:/app
    command: sh -c "go install github.com/air-verse/air@latest && air"
    ports:
      - "${FATURAMENTO_PORT:-5001}:${FATURAMENTO_PORT:-5001}"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - korp_net

  frontend:
    image: node:22-alpine
    container_name: korp_frontend_dev
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --proxy-config proxy.conf.js"
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    environment:
      - NODE_ENV=development
      - ESTOQUE_HOST=estoque
      - FATURAMENTO_HOST=faturamento
      - ESTOQUE_PORT=${ESTOQUE_PORT:-5002}
      - FATURAMENTO_PORT=${FATURAMENTO_PORT:-5001}
    depends_on:
      - estoque
      - faturamento
    networks:
      - korp_net

volumes:
  pgdata:

networks:
  korp_net:
    driver: bridge